// Knowledge Base — curated from MCP libraries (marketing-library + university-library)
// Refresh quarterly or when new books are added to the libraries

export const KNOWLEDGE_DOMAINS = [
  {
    id: 'behavioral_science',
    label: 'Behavioral Science',
    color: '#f59e0b',
    icon: '🧠',
    description: 'How humans actually decide. Biases, heuristics, and the gap between rational models and real behavior.',
  },
  {
    id: 'brand_effectiveness',
    label: 'Brand Effectiveness',
    color: '#22c55e',
    icon: '📈',
    description: 'What the evidence says about how brands grow. Mental availability, penetration, and the long vs. short.',
  },
  {
    id: 'consumer_psychology',
    label: 'Consumer Psychology',
    color: '#a78bfa',
    icon: '🔍',
    description: 'The messy middle of purchase decisions. Attention, framing, and context shape what people buy.',
  },
  {
    id: 'leadership_strategy',
    label: 'Leadership & Strategy',
    color: '#f87171',
    icon: '🧭',
    description: 'Strategic frameworks that hold up under pressure. Competitive advantage, change management, and organizational design.',
  },
  {
    id: 'marketing_innovation',
    label: 'Marketing Innovation',
    color: '#38bdf8',
    icon: '💡',
    description: 'Where marketing is going. AI visibility, generative engines, digital transformation, and what the research says works.',
  },
  {
    id: 'persuasion_influence',
    label: 'Persuasion & Influence',
    color: '#fb923c',
    icon: '🎯',
    description: 'The science of changing minds. From Cialdini\'s principles to pre-suasion and modern influence research.',
  },
];

export const CURATED_INSIGHTS = [
  // ═══════════════════════════════════════════════
  // BEHAVIORAL SCIENCE (12 entries)
  // ═══════════════════════════════════════════════

  {
    id: 'bs-001',
    domain: 'behavioral_science',
    source: { author: 'Daniel Kahneman', book: 'Thinking, Fast and Slow' },
    framework: 'System 1 vs System 2 Thinking',
    insight: 'Most decisions are made by fast, intuitive System 1 — not deliberate, analytical System 2. System 1 is the secret author of many choices and judgments. Marketers who design for System 2 rationality are designing for a brain that rarely shows up.',
    contentHooks: [
      'Why your carefully reasoned value proposition is being ignored',
      'The dashboard nobody reads: when data-driven marketing hits System 1',
      'Most marketing strategies assume a rational customer. The research says otherwise.',
    ],
    linkedinAngle: 'One provocative implication of System 1 for marketing practice — e.g. why rational USPs fail',
    newsletterAngle: 'Deep dive into System 1/2 with 2-3 real-world marketing implications and what to do instead',
  },
  {
    id: 'bs-002',
    domain: 'behavioral_science',
    source: { author: 'Daniel Kahneman', book: 'Thinking, Fast and Slow' },
    framework: 'Anchoring Effect',
    insight: 'The first number people encounter disproportionately influences subsequent judgments, even when arbitrary. Applies to pricing, budget negotiations, and performance targets. In one study, even spinning a wheel of fortune influenced estimates of African countries in the UN.',
    contentHooks: [
      'Why the first number in a budget meeting determines the outcome',
      'The pricing mistake that costs brands millions — and Kahneman explains why',
      'How an arbitrary number shapes your team\'s entire media plan',
    ],
    linkedinAngle: 'One anchoring story from marketing practice — e.g. how the first budget number wins',
    newsletterAngle: 'Anchoring in marketing: pricing, media budgets, KPI setting, and how to use it ethically',
  },
  {
    id: 'bs-003',
    domain: 'behavioral_science',
    source: { author: 'Richard Shotton', book: 'The Choice Factory' },
    framework: 'The Pratfall Effect',
    insight: 'Brands that admit a flaw become more appealing, not less. Avis\'s "We\'re number two, so we try harder" worked because imperfection signals authenticity. But it only works for brands already perceived as competent — for weak brands, flaws confirm incompetence.',
    contentHooks: [
      'The bias that makes imperfect brands more trustworthy',
      'Why your competitor\'s public mistake might be their best marketing move',
      'Avis beat Hertz by admitting they were worse. Here is the science behind it.',
    ],
    linkedinAngle: 'The pratfall effect applied to brand strategy: why admitting weakness builds trust',
    newsletterAngle: 'Tour of the pratfall effect with examples, boundary conditions, and practical application',
  },
  {
    id: 'bs-004',
    domain: 'behavioral_science',
    source: { author: 'Richard Shotton', book: 'The Choice Factory' },
    framework: '25 Cognitive Biases That Shape Every Purchase',
    insight: 'Shotton maps 25 biases to marketing applications — from social proof to the curse of knowledge. Each backed by experimental evidence. The key insight: most marketers know 3-4 biases. The other 21 are untapped competitive advantages.',
    contentHooks: [
      '25 biases shape every purchase decision. Most marketers know 3.',
      'The cognitive bias your creative team has never heard of',
      'Why behavioral science is the most underused weapon in marketing',
    ],
    linkedinAngle: 'Pick one overlooked bias (not social proof), one experiment, one marketing implication',
    newsletterAngle: 'Tour of 3-4 lesser-known biases with practical application frameworks',
  },
  {
    id: 'bs-005',
    domain: 'behavioral_science',
    source: { author: 'Dan Ariely', book: 'Predictably Irrational' },
    framework: 'The Decoy Effect and Relative Pricing',
    insight: 'People don\'t evaluate options in absolute terms — they compare. Adding a decoy option (clearly inferior to one choice but not the other) shifts preferences dramatically. The Economist pricing study: print-only ($59), web-only ($125), print+web ($125). Removing the "useless" print-only option changed which package people chose.',
    contentHooks: [
      'The pricing trick that shifts preferences without changing the product',
      'Why adding a bad option to your lineup can double sales of the good one',
      'Dan Ariely proved we don\'t know what we want — and how marketers can use that',
    ],
    linkedinAngle: 'The decoy effect in pricing: one specific experiment with one marketing takeaway',
    newsletterAngle: 'Relativity in decision-making: pricing, product tiers, and media plan architecture',
  },
  {
    id: 'bs-006',
    domain: 'behavioral_science',
    source: { author: 'Richard Thaler & Cass Sunstein', book: 'Nudge' },
    framework: 'Choice Architecture and Default Settings',
    insight: 'The way choices are presented dramatically affects outcomes. Organ donation rates differ by 60+ percentage points between opt-in and opt-out countries — not because of different preferences, but different defaults. The person who designs the form is a choice architect whether they know it or not.',
    contentHooks: [
      'The invisible person who decides 90% of outcomes: the choice architect',
      'Why your checkout flow is a behavioral science experiment you didn\'t design',
      'Default settings are the most powerful marketing tool nobody talks about',
    ],
    linkedinAngle: 'One example of choice architecture in marketing (checkout, pricing page, email signup)',
    newsletterAngle: 'Choice architecture for marketers: defaults, friction, and the ethics of nudging',
  },
  {
    id: 'bs-007',
    domain: 'behavioral_science',
    source: { author: 'Daniel Kahneman & Amos Tversky', book: 'Prospect Theory' },
    framework: 'Loss Aversion and Framing Effects',
    insight: 'Losses loom roughly twice as large as equivalent gains. People who would reject a 50/50 bet to lose $100 or gain $150 are not irrational — they are loss averse. Framing the same outcome as a gain vs. loss changes decisions dramatically. "90% survival rate" vs "10% mortality rate" changes medical choices.',
    contentHooks: [
      'Your customers fear losing $10 more than they desire gaining $20',
      'The framing experiment that changed economics forever — and what it means for your landing page',
      'Why "don\'t miss out" outperforms "get started" — Kahneman explains',
    ],
    linkedinAngle: 'Loss aversion in one marketing context: copy, pricing, or churn prevention',
    newsletterAngle: 'Prospect theory for marketers: loss aversion, framing, and the S-shaped value function',
  },
  {
    id: 'bs-008',
    domain: 'behavioral_science',
    source: { author: 'Rory Sutherland', book: 'Alchemy' },
    framework: 'Psycho-Logic vs Logic',
    insight: 'The opposite of a good idea can also be a good idea. Logic says reduce the journey time. Psycho-logic says put WiFi on the train. Human problems rarely have logical solutions — they have psychological ones. "A flower is simply a weed with an advertising budget." The danger of purely rational frameworks is they kill off magic.',
    contentHooks: [
      'Why the opposite of a good marketing strategy can also be a good strategy',
      'Rory Sutherland says your rational framework is killing creativity. He is probably right.',
      'The $300M train line problem that a $50 WiFi router could have solved',
    ],
    linkedinAngle: 'One Sutherland rule of alchemy applied to a marketing problem — be provocative',
    newsletterAngle: 'Psycho-logic in marketing: when rational optimization produces irrational outcomes',
  },
  {
    id: 'bs-009',
    domain: 'behavioral_science',
    source: { author: 'Annie Duke', book: 'Thinking in Bets' },
    framework: 'Resulting: Judging Decisions by Outcomes',
    insight: 'We judge the quality of decisions by their outcomes, not their process. A good decision can produce a bad result and vice versa. In poker, this is called "resulting." In marketing, it means a campaign that worked might have been a bad strategy that got lucky — and the campaign that flopped might have been brilliant.',
    contentHooks: [
      'Your most successful campaign might have been your worst decision',
      'Why marketing attribution is often just sophisticated resulting',
      'The poker concept every CMO should learn before their next budget meeting',
    ],
    linkedinAngle: 'Resulting in marketing: when we confuse luck for skill in campaign analysis',
    newsletterAngle: 'Decision quality vs outcome quality: poker thinking applied to marketing strategy',
  },
  {
    id: 'bs-010',
    domain: 'behavioral_science',
    source: { author: 'Richard Shotton', book: 'The Illusion of Choice' },
    framework: 'The Door-in-the-Face Technique and Reciprocity',
    insight: 'Ask for something large first, get rejected, then ask for what you actually want. Compliance rates soar. In Cialdini\'s study, asking students to escort juvenile delinquents on a zoo trip: direct ask got 17% compliance. Starting with "volunteer 2 hours/week for 2 years" then pivoting to the zoo trip got 50% — and 85% of those who committed actually showed up.',
    contentHooks: [
      'The negotiation technique that triples compliance rates',
      'Why your first ask should always be unreasonably large',
      'From Cialdini\'s lab to your pricing page: the door-in-the-face effect',
    ],
    linkedinAngle: 'Door-in-the-face applied to one marketing scenario: pricing tiers, sales calls, or proposal strategy',
    newsletterAngle: 'Sequential request strategies: door-in-the-face, foot-in-the-door, and when to use each',
  },
  {
    id: 'bs-011',
    domain: 'behavioral_science',
    source: { author: 'Nancy Harhut', book: 'Using Behavioral Science in Marketing' },
    framework: 'Hardwired Responses in Marketing',
    insight: 'Humans have automatic, instinctive, reflexive reactions to choices. In an innate effort to conserve mental energy, they rely on hardwired responses rather than well-considered decisions. The advantage for marketers: these automatic behaviors are predictable — and they can be prompted or triggered.',
    contentHooks: [
      'Your customer\'s brain is on autopilot. Here is how to work with it, not against it.',
      'The predictable patterns behind "irrational" consumer behavior',
      'Why behavioral science is the operating system upgrade marketing needs',
    ],
    linkedinAngle: 'One hardwired response applied to a specific marketing tactic (email, ads, landing pages)',
    newsletterAngle: 'The marketer\'s guide to hardwired human responses: which ones matter and how to trigger them',
  },
  {
    id: 'bs-012',
    domain: 'behavioral_science',
    source: { author: 'Daniel Kahneman, Olivier Sibony & Cass Sunstein', book: 'Noise' },
    framework: 'Noise vs Bias in Decision-Making',
    insight: 'We focus on bias (systematic error) but ignore noise (random variability). Two doctors given the same patient often give different diagnoses. Two marketing managers given the same data often make different budget decisions. Noise is harder to detect than bias but equally costly. Organizations are far noisier than they believe.',
    contentHooks: [
      'Your marketing team disagrees more than you think — and it is costing you',
      'The hidden flaw in every planning meeting: noise',
      'Why two analysts looking at the same data reach different conclusions — and what to do about it',
    ],
    linkedinAngle: 'Noise in marketing decisions: why consistency matters as much as accuracy',
    newsletterAngle: 'Noise audits for marketing teams: how to find and reduce random variability in decisions',
  },

  // ═══════════════════════════════════════════════
  // BRAND EFFECTIVENESS (10 entries)
  // ═══════════════════════════════════════════════

  {
    id: 'be-001',
    domain: 'brand_effectiveness',
    source: { author: 'Byron Sharp', book: 'How Brands Grow' },
    framework: 'Mental Availability and Brand Salience',
    insight: 'Brands grow primarily by increasing mental availability — the probability a buyer will notice, recognize, or think of a brand in buying situations. This depends on the quality and quantity of memory structures. Most marketing overcomplicates this: the primary job is to be easy to think of and easy to find.',
    contentHooks: [
      'The one metric that predicts brand growth better than anything else',
      'Byron Sharp says most brand strategy is wrong. Here is what the data shows.',
      'Why being remembered beats being differentiated',
    ],
    linkedinAngle: 'Mental availability as the overlooked growth driver — challenge the differentiation obsession',
    newsletterAngle: 'Mental availability deep dive: what it is, how to measure it, and why it beats positioning',
  },
  {
    id: 'be-002',
    domain: 'brand_effectiveness',
    source: { author: 'Byron Sharp', book: 'How Brands Grow' },
    framework: 'Double Jeopardy Law',
    insight: 'Small brands suffer twice: they have fewer buyers AND those buyers are slightly less loyal. It is not that small brands fail at loyalty — it is a mathematical regularity. Brands primarily grow by increasing penetration (getting more buyers), not by increasing loyalty among existing ones. Loyalty is largely a function of size.',
    contentHooks: [
      'The mathematical law that says your loyalty program probably doesn\'t work',
      'Why chasing loyalty is a trap for small brands — and what to do instead',
      'Double jeopardy: the law of physics that governs brand growth',
    ],
    linkedinAngle: 'Double jeopardy challenges a common marketing belief — penetration beats loyalty',
    newsletterAngle: 'How brands actually grow: penetration, double jeopardy, and the loyalty illusion',
  },
  {
    id: 'be-003',
    domain: 'brand_effectiveness',
    source: { author: 'Les Binet & Peter Field', book: 'The Long and the Short of It' },
    framework: 'The 60/40 Rule and Effectiveness Over Time',
    insight: 'Analysis of 996 campaigns shows brand building and sales activation work differently. Short-term activation drives immediate sales but effects decay quickly. Brand building creates long-term growth. The optimal balance: roughly 60% brand, 40% activation. But short-termism is destroying marketing effectiveness — too many brands have shifted too far toward activation.',
    contentHooks: [
      'The 996-campaign study that proves most marketing budgets are wrong',
      'Why your performance marketing is cannibalizing your future growth',
      'Binet & Field say 60% brand, 40% performance. Most brands do the opposite.',
    ],
    linkedinAngle: '60/40 rule applied to current over-investment in performance marketing',
    newsletterAngle: 'The long and short of marketing effectiveness: what 996 campaigns teach us about budget allocation',
  },
  {
    id: 'be-004',
    domain: 'brand_effectiveness',
    source: { author: 'Binet & Field / LinkedIn B2B Institute', book: 'ESOV Research' },
    framework: 'Extra Share of Voice (ESOV) and Growth',
    insight: 'Brands that set their share of voice above their share of market tend to grow. Those that set SOV below SOM tend to shrink. Growth is proportional to Extra SOV (SOV minus SOM). This rule has held for 50 years across B2C and now B2B: roughly +0.6% market share per year for every 10% ESOV.',
    contentHooks: [
      'The 50-year-old rule that still predicts brand growth better than any AI model',
      'The formula for brand growth that most CMOs ignore: ESOV',
      'Why outspending your market share is the surest path to growth',
    ],
    linkedinAngle: 'ESOV as a planning tool — why most brands underinvest and how to fix it',
    newsletterAngle: 'Share of voice economics: the ESOV rule, how to calculate it, and when it breaks down',
  },
  {
    id: 'be-005',
    domain: 'brand_effectiveness',
    source: { author: 'Jenni Romaniuk & Byron Sharp', book: 'How Brands Grow Part 2' },
    framework: 'Category Entry Points (CEPs)',
    insight: 'Brands are linked to buying situations through category entry points — the cues that trigger the brand in memory. A bank might be linked to "getting a mortgage," "saving for retirement," or "traveling abroad." Mental penetration (how many people link you to at least one CEP) and network size (how many CEPs you own) drive growth. Barclays has 78% mental penetration vs RBS at 53%.',
    contentHooks: [
      'The overlooked growth lever: category entry points',
      'Your brand is only as strong as the buying situations it owns',
      'Why brands should stop talking about positioning and start mapping CEPs',
    ],
    linkedinAngle: 'CEPs explained with one brand example — why buying situations matter more than positioning',
    newsletterAngle: 'Category entry points: how to map, measure, and expand your brand\'s mental network',
  },
  {
    id: 'be-006',
    domain: 'brand_effectiveness',
    source: { author: 'Binet & Field', book: 'Media in Focus' },
    framework: 'Reach as the Primary Driver of Effectiveness',
    insight: 'Analysis suggests reach accounts for around 83% of variations in media effectiveness. For most brands, the best strategy is to hit as many people as possible within the category. Frequency matters, but reach matters dramatically more. This challenges the hyper-targeting orthodoxy of digital marketing.',
    contentHooks: [
      'Reach explains 83% of media effectiveness. Targeting explains most of the rest — poorly.',
      'The inconvenient truth about hyper-targeting: reach still wins',
      'Why the best media strategy is often the simplest one',
    ],
    linkedinAngle: 'Reach vs targeting: the evidence says most brands over-target and under-reach',
    newsletterAngle: 'The reach imperative: why broad reach still beats precision targeting for most brands',
  },
  {
    id: 'be-007',
    domain: 'brand_effectiveness',
    source: { author: 'Jenni Romaniuk', book: 'Building Distinctive Brand Assets' },
    framework: 'Distinctive Brand Assets and the Asset Grid',
    insight: 'Our brain filters out 99.99% of stimuli. Brand assets (colors, logos, sonic cues, characters) are the hooks that survive this filter. The Distinctive Asset Grid measures fame (do people recognize it?) and uniqueness (do they connect it to only your brand?). Assets in the top-right quadrant are gold. Most brands have fewer distinctive assets than they think.',
    contentHooks: [
      'Your brain ignores 99.99% of marketing. Brand assets are the 0.01% that survives.',
      'The brand asset audit most marketers have never done — but should',
      'Why your logo rebrand might be destroying millions in brand equity',
    ],
    linkedinAngle: 'Distinctive brand assets: why consistency beats creativity in brand identity',
    newsletterAngle: 'The Distinctive Asset Grid: how to audit, build, and protect your brand\'s recognition shortcuts',
  },
  {
    id: 'be-008',
    domain: 'brand_effectiveness',
    source: { author: 'IPA / WARC', book: 'Effectiveness in Context' },
    framework: 'Brand Building Takes Over After 6 Months',
    insight: 'Sales activation is the primary driver of short-term effects. But brand building takes over as the primary driver of growth from sales activation after six months. Campaigns optimized purely for short-term metrics systematically destroy long-term brand health. The measurement systems most companies use are biased toward what is easy to measure (short-term) not what matters (long-term).',
    contentHooks: [
      'Your attribution model has a blind spot — it is called the long term',
      'Why optimizing for this quarter is destroying next year\'s growth',
      'The 6-month rule that separates great marketing from good marketing',
    ],
    linkedinAngle: 'The measurement trap: why attribution models undervalue brand building',
    newsletterAngle: 'Effectiveness in context: what changes when you measure marketing over 6 months, 1 year, and 3 years',
  },
  {
    id: 'be-009',
    domain: 'brand_effectiveness',
    source: { author: 'WARC / Ehrenberg-Bass', book: 'When Brands Go Dark' },
    framework: 'What Happens When Brands Stop Advertising',
    insight: 'When brands stop advertising, sales decline — but not immediately. The delay creates a dangerous illusion: cutting ad spend looks like a cost saving in Q1, but the damage compounds over quarters. Brands that went dark saw market share erosion that took years and significantly more spend to recover. This is why cutting marketing budgets in a recession feels smart but compounds the damage.',
    contentHooks: [
      'The brand that cut its ad budget and saved millions — then lost more',
      'The slow-motion car crash of going dark: what the research actually shows',
      'Why CFOs who cut marketing budgets are optimizing for the wrong quarter',
    ],
    linkedinAngle: 'The danger of going dark: what happens when brands stop advertising (with data)',
    newsletterAngle: 'Going dark: the compounding cost of marketing budget cuts and when silence kills brands',
  },
  {
    id: 'be-010',
    domain: 'brand_effectiveness',
    source: { author: 'Phil Barden', book: 'Decoded' },
    framework: 'The Net Value Equation (Reward minus Cost)',
    insight: 'Every purchase is a trade-off between perceived reward and perceived cost. Cost is not just price — it includes behavioral cost (effort, friction, complexity). The brain\'s autopilot constantly calculates this net value. Reducing friction often outperforms increasing reward. In one study, making milk easier to reach increased healthy choices more than any messaging.',
    contentHooks: [
      'The equation your customer\'s brain runs before every purchase — and it is not about price',
      'Why reducing friction beats adding features every time',
      'The milk experiment that explains more about marketing than most strategy decks',
    ],
    linkedinAngle: 'Net value equation: why reducing friction beats increasing reward in most marketing contexts',
    newsletterAngle: 'Decoded: how the brain calculates value, and what that means for pricing, UX, and conversion',
  },

  // ═══════════════════════════════════════════════
  // CONSUMER PSYCHOLOGY (8 entries)
  // ═══════════════════════════════════════════════

  {
    id: 'cp-001',
    domain: 'consumer_psychology',
    source: { author: 'Google / Alistair Rennie & Jonny Protheroe', book: 'Decoding Decisions: The Messy Middle' },
    framework: 'The Messy Middle of Purchase Behavior',
    insight: 'Between trigger and purchase lies a messy middle of exploration and evaluation. Consumers loop between these two modes — expanding options then narrowing — using cognitive shortcuts (category heuristics, social proof, authority bias, power of free, scarcity). Brands that apply these behavioral science principles at the right moment in the messy middle can shift preference from first-choice to second-choice brands.',
    contentHooks: [
      'Google mapped the messy middle of purchase decisions. Most funnels are fiction.',
      'The 6 biases that decide who wins in the messy middle',
      'Why the marketing funnel is dead — and what replaces it',
    ],
    linkedinAngle: 'The messy middle challenges the linear funnel — one specific bias applied to purchase decisions',
    newsletterAngle: 'The messy middle decoded: exploration, evaluation, and the 6 biases that determine brand choice',
  },
  {
    id: 'cp-002',
    domain: 'consumer_psychology',
    source: { author: 'Gerald Zaltman', book: 'How Customers Think' },
    framework: 'The 95% Unconscious Mind',
    insight: 'At least 95% of cognition happens below conscious awareness. Customers cannot reliably tell you why they buy what they buy. Focus groups and surveys tap into the 5% — the post-hoc rationalization, not the real driver. The overlap among multiple disciplines (sociology, linguistics, neuroscience) provides more insight than asking people directly.',
    contentHooks: [
      '95% of purchase decisions happen below the surface. You are surveying the wrong 5%.',
      'Why focus groups lie — and what to do instead',
      'The Harvard study that says your customer research methodology is fundamentally flawed',
    ],
    linkedinAngle: 'Why declared data is unreliable: the gap between what customers say and what they do',
    newsletterAngle: 'How customers actually think: unconscious cognition, metaphor elicitation, and beyond surveys',
  },
  {
    id: 'cp-003',
    domain: 'consumer_psychology',
    source: { author: 'Will Storr', book: 'The Status Game' },
    framework: 'Status as the Hidden Driver of Behavior',
    insight: 'Humans are compelled to play status games. We seek status through dominance (force), virtue (moral), or success (competence). Brands are status symbols whether they intend to be or not. Understanding which status game your customer plays explains purchasing behavior that "rational" models cannot — from luxury goods to ethical consumption to productivity tools.',
    contentHooks: [
      'Your customers are not buying products. They are buying status.',
      'The 3 status games that explain every purchase you have ever made',
      'Why ethical consumption is a status game — and why that is not a bad thing',
    ],
    linkedinAngle: 'One of the three status games applied to a brand category (luxury, SaaS, FMCG)',
    newsletterAngle: 'The status game in marketing: dominance, virtue, and success as purchase drivers',
  },
  {
    id: 'cp-004',
    domain: 'consumer_psychology',
    source: { author: 'Will Storr', book: 'The Science of Storytelling' },
    framework: 'Why Brains Are Wired for Story',
    insight: 'The brain is a storytelling machine that constantly constructs cause-and-effect narratives to make sense of the world. Stories trigger neural coupling — the listener\'s brain mirrors the teller\'s. This is why data and facts alone fail to persuade, while a well-told story changes minds. The best brand narratives work because they follow the same structures the brain is wired to process.',
    contentHooks: [
      'Neuroscience explains why your data-heavy pitch loses to a good story every time',
      'The brain does not process information. It processes stories.',
      'Why brand storytelling works — the neuroscience behind neural coupling',
    ],
    linkedinAngle: 'Neural coupling and storytelling: why story beats data in persuasion',
    newsletterAngle: 'The neuroscience of brand storytelling: how stories hijack the brain and what that means for marketing',
  },
  {
    id: 'cp-005',
    domain: 'consumer_psychology',
    source: { author: 'Google', book: 'Decoding Decisions Part II' },
    framework: 'Default Bias and Endowment Effect in E-commerce',
    insight: 'In online shopping experiments, default options and endowment effects dramatically shifted purchase behavior. When shoppers could visualize a sofa in their own home (triggering endowment), consideration increased. Default delivery options steered choices. The factors that inspire shopper confidence are the same that increase purchase consideration.',
    contentHooks: [
      'Google tested which biases actually move the needle in e-commerce. Here are the winners.',
      'The default option experiment that should change how you design checkout flows',
      'Why letting customers "try before they buy" works — but not for the reason you think',
    ],
    linkedinAngle: 'Default bias in e-commerce: one experiment, one design implication',
    newsletterAngle: 'Behavioral science in e-commerce: what Google\'s experiments reveal about online purchase decisions',
  },
  {
    id: 'cp-006',
    domain: 'consumer_psychology',
    source: { author: 'Herbert Simon', book: 'Designing Organizations for an Information-Rich World' },
    framework: 'The Attention Economy',
    insight: 'A wealth of information creates a poverty of attention. Simon wrote this in 1971, and it has only become more relevant. Attention is the scarce resource in marketing, not information. Brands compete not just against competitors but against everything vying for a finite pool of human attention. The cost of attention is the real media cost.',
    contentHooks: [
      'Herbert Simon predicted the attention crisis in 1971. We still have not listened.',
      'The real cost of your ad is not the media spend — it is the attention you demand',
      'Information is free. Attention is the currency. Most brands are still selling information.',
    ],
    linkedinAngle: 'Attention as the scarcest resource in marketing — one practical implication',
    newsletterAngle: 'The attention economy: Simon\'s 1971 prediction, the true cost of advertising attention, and what it means now',
  },
  {
    id: 'cp-007',
    domain: 'consumer_psychology',
    source: { author: 'Robert Sapolsky', book: 'Behave: The Biology of Humans at Our Best and Worst' },
    framework: 'Context Determines Behavior More Than Character',
    insight: 'Human behavior is not driven by fixed character traits but by context — what happened seconds, hours, days, and years before the action. The same person can be generous or selfish depending on context. For marketing: the situation in which someone encounters your brand matters more than their demographic profile or persona.',
    contentHooks: [
      'Your customer persona is a fiction. Context determines behavior, not character.',
      'The neuroscience that says demographic targeting misses the point',
      'Why the same person buys premium on Tuesday and discount on Thursday',
    ],
    linkedinAngle: 'Context over character: why targeting by situation beats targeting by persona',
    newsletterAngle: 'Behavioral biology meets marketing: why context shapes purchase behavior more than demographics',
  },
  {
    id: 'cp-008',
    domain: 'consumer_psychology',
    source: { author: 'Richard Shotton', book: 'The Illusion of Choice' },
    framework: 'The Cocktail Party Effect and Personalization',
    insight: 'Personalizing a social proof message makes it more potent. Cialdini\'s hotel towel study: "Most guests reuse their towels" got 44% reuse. "Most guests in this room reuse their towels" got 49%. The cocktail party effect — we notice our own name in a noisy room — means even basic personalization cuts through attention filters.',
    contentHooks: [
      'The 5-word change that increased compliance by 11% — and why it works',
      'Personalization is not about recommendations. It is about the cocktail party effect.',
      'Why "people like you" is the most powerful phrase in marketing',
    ],
    linkedinAngle: 'Personalized social proof: one small change, one big behavioral shift',
    newsletterAngle: 'The science of personalization: cocktail party effect, social proof, and what "relevant" actually means',
  },

  // ═══════════════════════════════════════════════
  // LEADERSHIP & STRATEGY (8 entries)
  // ═══════════════════════════════════════════════

  {
    id: 'ls-001',
    domain: 'leadership_strategy',
    source: { author: 'John Kotter', book: 'Leading Change / Our Iceberg Is Melting' },
    framework: 'Kotter\'s 8 Steps of Change Management',
    insight: 'Most change initiatives fail not because the strategy is wrong but because the implementation ignores human factors. Kotter\'s 8 steps: create urgency, form a coalition, create vision, communicate vision, remove obstacles, create short-term wins, build on the change, anchor in culture. The most common failure: declaring victory too soon.',
    contentHooks: [
      'Why 70% of transformations fail — and it is not the strategy',
      'The change management mistake that kills marketing transformations',
      'Kotter says you are probably declaring victory too soon. Here is how to tell.',
    ],
    linkedinAngle: 'One step from Kotter\'s framework applied to marketing team transformation',
    newsletterAngle: 'Leading marketing transformation: Kotter\'s 8 steps applied to the shift from traditional to digital',
  },
  {
    id: 'ls-002',
    domain: 'leadership_strategy',
    source: { author: 'Rita Gunther McGrath', book: 'The End of Competitive Advantage' },
    framework: 'Transient Advantage Replaces Sustainable Advantage',
    insight: 'The idea of sustainable competitive advantage is dead. In fast-moving markets, advantage is transient — companies must continuously launch new strategic initiatives, exploit them, and then move on before they become irrelevant. The companies that thrive are not the ones that defend one position forever, but those that continuously reconfigure.',
    contentHooks: [
      'Porter\'s competitive advantage framework is broken. Here is what replaces it.',
      'Why defending your market position is the surest way to lose it',
      'The marketing strategy that assumes permanence in a world of transience',
    ],
    linkedinAngle: 'Transient advantage: why the best marketing strategy is the one that expects to evolve',
    newsletterAngle: 'The end of competitive advantage: what transient strategy means for marketing planning',
  },
  {
    id: 'ls-003',
    domain: 'leadership_strategy',
    source: { author: 'Michael Porter', book: 'Competitive Strategy / Value Chain' },
    framework: 'Value Chain Analysis and Competitive Forces',
    insight: 'Every company is a collection of activities that create value. The value chain framework decomposes these into primary activities (logistics, operations, marketing, sales, service) and support activities (infrastructure, HR, tech, procurement). Competitive advantage comes from performing these activities more cheaply or differently than competitors. The extended value chain includes suppliers and distributors — value can be created or destroyed at any link.',
    contentHooks: [
      'Porter\'s value chain is 40 years old. It is still the best tool for finding competitive advantage.',
      'Where in your value chain are you actually creating value? Most companies do not know.',
      'The value chain analysis that every marketing leader should do — but doesn\'t',
    ],
    linkedinAngle: 'Value chain thinking applied to marketing: where does marketing actually create value?',
    newsletterAngle: 'Porter\'s value chain for marketers: finding competitive advantage in a world of commoditized tactics',
  },
  {
    id: 'ls-004',
    domain: 'leadership_strategy',
    source: { author: 'BCG / UNIR', book: 'The Transformation Paradox' },
    framework: 'Digital Transformation Barriers: 1/3 Culture, 1/3 Technology, 1/3 Finance',
    insight: 'A survey of 600+ companies found transformation challenges split equally: one-third cultural, one-third technological, one-third financial. But the biggest single barrier was the lack of qualified people. Formal organizational structures are easier to change than culture — which is why most digital transformations fail despite good technology.',
    contentHooks: [
      'Digital transformation fails 66% of the time — and technology is only a third of the problem',
      'The transformation barrier nobody wants to talk about: culture',
      'You cannot install digital transformation. You have to grow it.',
    ],
    linkedinAngle: 'Culture as the hidden barrier to marketing transformation — one specific example',
    newsletterAngle: 'The transformation paradox: why technology is the easy part and culture is the hard part',
  },
  {
    id: 'ls-005',
    domain: 'leadership_strategy',
    source: { author: 'Kaplan & Norton', book: 'Balanced Scorecard' },
    framework: 'Strategy Execution via the Balanced Scorecard',
    insight: 'Most strategies fail at execution, not formulation. The Balanced Scorecard connects strategy to operations through four perspectives: financial, customer, internal processes, and learning/growth. As planning horizons shorten due to market uncertainty, continuous evaluation replaces annual planning. Combined with business intelligence, it allows real-time strategy adjustment.',
    contentHooks: [
      'Your strategy is only as good as your ability to measure it — across 4 dimensions',
      'Why annual marketing plans are dead and what replaces them',
      'The measurement framework that connects marketing activity to business outcomes',
    ],
    linkedinAngle: 'The BSC applied to marketing: measuring what matters beyond ROAS',
    newsletterAngle: 'Strategy execution for marketing leaders: the balanced scorecard meets modern marketing measurement',
  },
  {
    id: 'ls-006',
    domain: 'leadership_strategy',
    source: { author: 'Peter Senge', book: 'The Fifth Discipline' },
    framework: 'The Learning Organization',
    insight: 'Organizations that thrive are those that learn faster than the environment changes. The five disciplines: personal mastery, mental models, shared vision, team learning, and systems thinking. Systems thinking is the "fifth discipline" that integrates all others. Most organizations are trapped by their own mental models — assumptions they do not even know they hold.',
    contentHooks: [
      'The mental models your marketing team does not know it has — and they are killing your strategy',
      'Why the best marketing teams are learning organizations, not executing machines',
      'Systems thinking: the skill gap nobody is talking about in marketing leadership',
    ],
    linkedinAngle: 'Mental models in marketing: the invisible assumptions that constrain strategy',
    newsletterAngle: 'Building a learning marketing organization: Senge\'s five disciplines applied to marketing teams',
  },
  {
    id: 'ls-007',
    domain: 'leadership_strategy',
    source: { author: 'UNIR Estrategia', book: 'Resources and Capabilities Framework' },
    framework: 'Resource-Based View of Competitive Advantage',
    insight: 'Competitive advantage comes from resources and capabilities that are valuable, rare, inimitable, and non-substitutable (VRIN). Each company\'s resources are unique — you cannot copy what makes another company successful because their capabilities are embedded in their specific history, culture, and processes. Strategy should be designed from the inside out.',
    contentHooks: [
      'Stop copying your competitor\'s strategy. Their advantage cannot be replicated.',
      'The strategic framework that explains why best practices are often worst practices',
      'Why your company\'s unique capabilities matter more than market positioning',
    ],
    linkedinAngle: 'Resource-based view: why copying competitors\' marketing strategy is always a losing game',
    newsletterAngle: 'Inside-out strategy: the resource-based view and why your unique capabilities are your real moat',
  },
  {
    id: 'ls-008',
    domain: 'leadership_strategy',
    source: { author: 'UNIR Estrategia / Darwin principle', book: 'Gestión del Cambio' },
    framework: 'Organizational Inertia and the 5 Companies That Failed to Adapt',
    insight: 'It is not the strongest species that survives, nor the most intelligent, but the one most responsive to change. Kodak designed one of the first digital cameras but did not adapt. Nokia missed the smartphone shift. Pan Am assumed transatlantic travel would always grow. Organizational inertia — routines, power structures, institutional isomorphism — kills more strategies than bad ideas.',
    contentHooks: [
      'Kodak invented the future and then refused to use it. Your marketing org might be doing the same.',
      'The 5 companies that died because they could not change — and the warning signs they missed',
      'Organizational inertia is the silent killer of marketing innovation',
    ],
    linkedinAngle: 'One organizational inertia pattern (routines, power structures, or imitation) applied to marketing',
    newsletterAngle: 'Why good companies fail: organizational inertia, adaptation failure, and what marketing leaders can learn',
  },

  // ═══════════════════════════════════════════════
  // MARKETING INNOVATION (8 entries)
  // ═══════════════════════════════════════════════

  {
    id: 'mi-001',
    domain: 'marketing_innovation',
    source: { author: 'Ahrefs / Multiple researchers', book: 'AI Brand Visibility Research 2025' },
    framework: 'AI Visibility: How Brands Appear in ChatGPT and AI Search',
    insight: 'ChatGPT mentions brands 3.2x more often than it provides clickable citations. AI search visitors convert at 4.4x higher rates than traditional organic search. 77% of ChatGPT users use it as a search engine. Most brands have not optimized for AI mentions yet — creating a first-mover advantage window. The brands that win in AI search are those with varied digital profiles, not just high domain authority.',
    contentHooks: [
      'Your brand is being recommended (or ignored) by ChatGPT right now. Do you know which?',
      'AI search visitors convert at 4.4x the rate. Most brands are still optimizing for Google.',
      'The new brand visibility crisis: if AI cannot find you, neither can your customers.',
    ],
    linkedinAngle: 'AI brand visibility as the next SEO: one specific data point about how LLMs recommend brands',
    newsletterAngle: 'AI visibility: how ChatGPT, Gemini, and AI search are reshaping brand discovery and what to do about it',
  },
  {
    id: 'mi-002',
    domain: 'marketing_innovation',
    source: { author: 'Carnegie Mellon / Pranjal Aggarwal et al.', book: 'GEO: Generative Engine Optimization' },
    framework: 'Generative Engine Optimization (GEO)',
    insight: 'Generative engines remove the need to navigate to websites by providing comprehensive responses directly. This threatens traditional SEO and content marketing. GEO research shows specific content strategies — citing sources, adding statistics, using quotations from authoritative sources — increase visibility in AI-generated answers. The creators of content that trains and informs AI models are the new winners.',
    contentHooks: [
      'SEO is evolving into GEO. Here is what changes — and what stays the same.',
      'The research paper that defines the next decade of content marketing',
      'Generative Engine Optimization: why creating content for AI is now as important as creating it for humans',
    ],
    linkedinAngle: 'GEO basics: what content strategies work for AI visibility (cite stats, quote authorities)',
    newsletterAngle: 'From SEO to GEO: how generative engines change content strategy and what the research says works',
  },
  {
    id: 'mi-003',
    domain: 'marketing_innovation',
    source: { author: 'Everett Rogers', book: 'Diffusion of Innovations' },
    framework: 'The Innovation Adoption Curve and Crossing the Chasm',
    insight: 'Innovation adoption follows a bell curve: innovators (2.5%), early adopters (13.5%), early majority (34%), late majority (34%), laggards (16%). The chasm between early adopters and early majority is where most innovations die. Geoffrey Moore showed that crossing this chasm requires shifting from visionary selling to pragmatist selling — a fundamentally different marketing approach.',
    contentHooks: [
      'The gap where most marketing innovations go to die — and how to cross it',
      'Why your early success with innovation adopters means nothing for mainstream growth',
      'Rogers mapped the adoption curve in 1962. It still explains why your new product is stuck.',
    ],
    linkedinAngle: 'The chasm in marketing tech adoption: why what works for early adopters fails for the majority',
    newsletterAngle: 'Crossing the chasm: Rogers\' diffusion theory applied to marketing technology adoption',
  },
  {
    id: 'mi-004',
    domain: 'marketing_innovation',
    source: { author: 'UNIR Innovación', book: 'Innovation Hubs and Intrapreneurship' },
    framework: 'Building Innovation Culture: Hubs, Hackathons, and Metrics',
    insight: 'AT&T\'s innovation pipeline: 50,000+ ideas submitted, 100+ products launched, EUR39M invested. IBM certified 100,000 employees in Design Thinking, reducing product development time by 75%. Google\'s Design Sprints reduced time-to-insight by 30%. The pattern: innovation culture requires dedicated spaces, structured methods, and measurable outcomes — not just permission to be creative.',
    contentHooks: [
      'AT&T turned 50,000 ideas into 100+ products. Here is the system behind it.',
      'Innovation culture is not about beanbags and brainstorms. It is about systems.',
      'IBM\'s 100,000-person Design Thinking certification: does it actually work?',
    ],
    linkedinAngle: 'One innovation culture metric that matters: structured ideation with measurable outcomes',
    newsletterAngle: 'Building innovation culture that scales: what AT&T, IBM, and Google actually do (with numbers)',
  },
  {
    id: 'mi-005',
    domain: 'marketing_innovation',
    source: { author: 'Takeuchi & Nonaka / UNIR', book: 'Scrum and Agile in Innovation' },
    framework: 'Agile Innovation: Scrum Applied Beyond Software',
    insight: 'Scrum originated from Takeuchi and Nonaka\'s 1986 article on product development — not software. Teams working in short sprints with continuous validation outperform teams following linear plans. Retrospectives drive learning. The key insight for marketing: agile is not about moving fast, it is about learning fast. 100% of product teams and 75% of commercial teams at Unilever Indonesia adopted agile, resulting in 35% faster development cycles.',
    contentHooks: [
      'Scrum was invented for product development, not software. Marketing should take the hint.',
      'Why your quarterly marketing plan should be replaced by 2-week sprints',
      'Agile marketing is not about speed. It is about learning. Here is the difference.',
    ],
    linkedinAngle: 'Agile in marketing: one specific practice (retrospectives, sprints) applied to campaign management',
    newsletterAngle: 'Agile innovation for marketing teams: from Takeuchi & Nonaka to modern sprint-based campaign management',
  },
  {
    id: 'mi-006',
    domain: 'marketing_innovation',
    source: { author: 'Harvard / SparkToro', book: 'AI Brand Recommendations Research' },
    framework: 'AI Recommendations Are Highly Inconsistent',
    insight: 'AI tools produce different brand recommendation lists nearly every time they are queried. Research shows AI visibility fluctuates significantly — a brand recommended today may be absent tomorrow. This inconsistency means marketers should not treat AI visibility as a one-time optimization but as an ongoing signal that requires continuous monitoring and content strategy.',
    contentHooks: [
      'AI brand recommendations change every time you ask. What does that mean for your strategy?',
      'The uncomfortable truth: AI visibility is volatile, not stable',
      'Why tracking your brand in ChatGPT is the new brand tracking — but harder',
    ],
    linkedinAngle: 'AI recommendation volatility: why AI brand monitoring is the new brand tracking',
    newsletterAngle: 'The instability of AI recommendations: implications for brand strategy and monitoring',
  },
  {
    id: 'mi-007',
    domain: 'marketing_innovation',
    source: { author: 'V. Kumar, Philip Kotler et al.', book: 'Generative AI in Marketing (2025)' },
    framework: 'GenAI Marketing: Promises, Perils, and Public Policy',
    insight: 'Generative AI in marketing creates both opportunity and risk. Vendors can manipulate LLM recommendations through "strategic text sequences" — transforming never-recommended products into frequently recommended ones. This raises ethical concerns about fair competition in AI-driven search. The public policy implications are significant: who governs AI recommendations when they increasingly determine what consumers see and buy?',
    contentHooks: [
      'Brands are already gaming AI recommendations. Here is how — and why it is a problem.',
      'The ethical dilemma of AI-powered marketing that nobody is talking about',
      'When ChatGPT recommends your competitor, is it because they are better — or because they gamed the system?',
    ],
    linkedinAngle: 'AI recommendation manipulation: the ethical line between optimization and gaming',
    newsletterAngle: 'GenAI and fair competition: how LLM recommendations are being gamed and what it means for marketing ethics',
  },
  {
    id: 'mi-008',
    domain: 'marketing_innovation',
    source: { author: 'UNIR Marketing', book: 'Omnichannel and Customer Experience' },
    framework: 'Omnichannel Marketing and the Seamless Experience',
    insight: 'Omnichannel is not about being present on every channel — it is about creating a seamless experience across channels. The customer does not think in channels. They think in needs. Marketing measurement, KPIs, and organizational structure must shift from channel-centric to customer-journey-centric. Most organizations are structured around channels, which creates friction at every handoff point.',
    contentHooks: [
      'Your org chart is your biggest omnichannel problem',
      'Customers do not think in channels. Your marketing team does. That is the problem.',
      'Why "omnichannel strategy" usually means "we are on lots of channels but none of them talk to each other"',
    ],
    linkedinAngle: 'The organizational barrier to omnichannel: why channel-centric org structures create friction',
    newsletterAngle: 'True omnichannel marketing: moving from channel presence to seamless customer experience',
  },

  // ═══════════════════════════════════════════════
  // PERSUASION & INFLUENCE (8 entries)
  // ═══════════════════════════════════════════════

  {
    id: 'pi-001',
    domain: 'persuasion_influence',
    source: { author: 'Robert Cialdini', book: 'Influence: The Psychology of Persuasion' },
    framework: 'The 6 Principles of Persuasion',
    insight: 'Six universal principles drive persuasion: reciprocity (return favors), commitment/consistency (honor past decisions), social proof (follow the crowd), authority (defer to experts), liking (agree with friends), and scarcity (want what is rare). These are not tricks — they are deeply embedded social norms that have evolved over millennia. Each can be applied ethically or manipulatively.',
    contentHooks: [
      'Cialdini identified 6 influence levers in 1984. They still explain most marketing that works.',
      'The influence principle most marketers overuse — and the one they ignore',
      'Why ethical persuasion is not an oxymoron: Cialdini\'s framework for influence with integrity',
    ],
    linkedinAngle: 'One Cialdini principle applied to a specific marketing challenge (not social proof — pick a less obvious one)',
    newsletterAngle: 'Cialdini\'s 6 principles in modern marketing: which still work, which are overused, and which are underused',
  },
  {
    id: 'pi-002',
    domain: 'persuasion_influence',
    source: { author: 'Robert Cialdini', book: 'Pre-Suasion' },
    framework: 'Pre-Suasion: The Power of What Comes Before',
    insight: 'What happens before a message dramatically affects how it is received. Cialdini calls this "pre-suasion" — the practice of arranging for recipients to be receptive to a message before they encounter it. Asking people if they consider themselves helpful before asking for a favor increases compliance. The moment of maximum influence is not when you make your case — it is the moment before.',
    contentHooks: [
      'The most important moment in your pitch is not the pitch. It is what comes before.',
      'Pre-suasion: why the opening slide of your deck determines the outcome of your meeting',
      'Cialdini says influence starts before you open your mouth. Here is how.',
    ],
    linkedinAngle: 'One pre-suasion technique applied to presentations, sales calls, or landing pages',
    newsletterAngle: 'Pre-suasion for marketers: how to prime audiences for receptivity before delivering the message',
  },
  {
    id: 'pi-003',
    domain: 'persuasion_influence',
    source: { author: 'Rory Sutherland', book: 'Alchemy' },
    framework: 'Rory\'s Rules of Alchemy',
    insight: 'Sutherland\'s 11 rules include: "The opposite of a good idea can be a good idea." "Don\'t design for average." "It doesn\'t pay to be logical if everyone else is being logical." "A good guess that stands up to observation is still science." These rules challenge the over-rationalization of marketing and argue for creative, psychological solutions over logical ones.',
    contentHooks: [
      '11 rules of alchemy that challenge everything you learned in business school',
      'Why being logical is a competitive disadvantage when everyone else is being logical too',
      'Rory Sutherland\'s case for irrational marketing — and why the data supports him',
    ],
    linkedinAngle: 'One rule of alchemy applied to a common marketing decision — be contrarian',
    newsletterAngle: 'Alchemy in marketing: Sutherland\'s 11 rules and what they mean for strategy, pricing, and creativity',
  },
  {
    id: 'pi-004',
    domain: 'persuasion_influence',
    source: { author: 'Howard Gossage', book: 'The Book of Gossage / Is There Any Hope for Advertising?' },
    framework: 'Nobody Reads Ads — They Read What Interests Them',
    insight: 'Gossage, the "Socrates of San Francisco," argued that people don\'t read ads — they read what interests them, and sometimes that is an ad. The implication: advertising must be genuinely interesting, not just well-targeted. He pioneered interactive advertising and believed the audience should participate, not just receive. His philosophy: respect the reader\'s intelligence.',
    contentHooks: [
      'Nobody reads ads. They read what interests them. Sometimes that is an ad.',
      'The advertising legend from 1960 who predicted content marketing',
      'Howard Gossage figured out the attention economy 50 years before it had a name',
    ],
    linkedinAngle: 'Gossage\'s philosophy applied to modern content marketing: make it interesting first',
    newsletterAngle: 'The Gossage principle: why advertising that respects intelligence outperforms advertising that interrupts',
  },
  {
    id: 'pi-005',
    domain: 'persuasion_influence',
    source: { author: 'Richard Shotton / Nudge-Vault', book: 'Compiled Behavioral Experiments' },
    framework: 'Social Proof: When It Works and When It Backfires',
    insight: 'Social proof is the most widely applied behavioral bias in marketing — but it has failure modes. Negative social proof backfires: "Most people evade taxes" increases evasion. Petrified Forest signs saying "Many visitors steal wood" increased theft. Social proof works best when it highlights the desired behavior, not the undesired one. Personalizing social proof ("people in this room") amplifies its effect.',
    contentHooks: [
      'Social proof is the most misused bias in marketing. Here is when it backfires.',
      'The sign that accidentally tripled theft — and what it teaches about social proof',
      'Why "join 10,000 customers" might be hurting your conversion rate',
    ],
    linkedinAngle: 'When social proof backfires: one negative social proof example with the fix',
    newsletterAngle: 'The social proof playbook: when it works, when it backfires, and how to personalize it',
  },
  {
    id: 'pi-006',
    domain: 'persuasion_influence',
    source: { author: 'Cialdini / Shotton', book: 'Influence + Nudge-Vault' },
    framework: 'The Foot-in-the-Door Technique',
    insight: 'Small commitments lead to larger ones. People who put small "Drive Safe" postcards in their windows were far more likely to later erect giant posters on their lawns. The mechanism: once people commit to a small action, they adjust their self-image to be consistent with that action — making the larger request feel natural rather than burdensome.',
    contentHooks: [
      'The tiny commitment that leads to big decisions — and how to engineer it',
      'Why your free trial works: it is not the product, it is the psychology',
      'Foot-in-the-door: the micro-commitment strategy that scales influence',
    ],
    linkedinAngle: 'Foot-in-the-door in digital marketing: one specific micro-commitment that leads to conversion',
    newsletterAngle: 'Commitment and consistency in marketing: foot-in-the-door, escalation, and the psychology of yes',
  },
  {
    id: 'pi-007',
    domain: 'persuasion_influence',
    source: { author: 'Oren Klaff', book: 'Pitch Anything' },
    framework: 'Frame Control in Pitches and Negotiations',
    insight: 'Every social interaction involves frame collision — your frame vs. theirs. The person who controls the frame controls the conversation. In pitches, the "prize frame" reverses the dynamic: instead of seeking approval, position yourself as the prize to be won. The "time frame" creates urgency. The "intrigue frame" uses narrative to bypass analytical resistance.',
    contentHooks: [
      'You are either controlling the frame or losing to it. There is no middle ground.',
      'The pitch technique that turns the power dynamic upside down',
      'Why the best marketers think in frames, not features',
    ],
    linkedinAngle: 'Frame control in marketing presentations: one specific technique to own the narrative',
    newsletterAngle: 'Frame control for marketers: how to set the terms of every conversation, pitch, and campaign',
  },
  {
    id: 'pi-008',
    domain: 'persuasion_influence',
    source: { author: 'Nudge-Vault / Multiple researchers', book: 'Behavioral Experiments Compilation' },
    framework: 'The Labour Illusion and Perceived Effort',
    insight: 'People value things more when they can see the effort behind them. A locksmith who opened doors too quickly got fewer tips. Travel sites that show a "searching 500 airlines" animation get higher satisfaction scores than instant results. When Duke University ran a "regret lottery" (you lose if you do not participate), survey completion doubled. Showing the work increases perceived value.',
    contentHooks: [
      'The locksmith paradox: why being too good at your job costs you',
      'Why slow-loading results pages get higher satisfaction scores than instant ones',
      'The labor illusion: how showing your work increases perceived value',
    ],
    linkedinAngle: 'The labour illusion applied to one marketing context: product demos, pricing, or service delivery',
    newsletterAngle: 'The science of perceived effort: why showing your work makes everything more valuable',
  },
];

// Helper: get insights by domain
export function getInsightsByDomain(domainId) {
  return CURATED_INSIGHTS.filter(i => i.domain === domainId);
}

// Helper: get insight by ID
export function getInsightById(id) {
  return CURATED_INSIGHTS.find(i => i.id === id);
}

// Helper: get domain by ID
export function getDomainById(id) {
  return KNOWLEDGE_DOMAINS.find(d => d.id === id);
}
